language: go
go:
  - "1.13"
script:
  - ./cover.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - ./build.sh
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: dist/*
  api_key:
    secure: cNQ6kDD8WlK4ImmnDZ7o/87V0wMRUuJpc5Djo9/Gh0SPNvYogv50HAP8BaXBSAWmxknqtab6lZdpz0ixchqFbx1abjYwl5F98nwzApkYsp0rRursu9jtkyJEUp3MgvnIt2FCnOCNTDZEKaHy9YOYw3HbcqQ4VQC9T7sPLylU8mFul6Ny7L+8GKHajR00IuE7MoQarZcMxf+x2XBf4cMt/9PEN/ylg4/i4DMb4dsWpt6P0dnO3KpQ5JY9PeRo/kpT9KFPvKXbgxz8LfZHlGlim9IH+0W0hrxjTCw/Gx9M1uQapyy9KIKH8dmV+bdOcPJdE1kvzC7NfZo/poJjBAmBAdmmTU36VgkavuTsQGwtEQXK9WvFnDZDzUWRFtOUzEnBH2YJZcCKzD98DZlqadkLTBxawmHkkvQc0pX/EfqvwPV1d0vv5EkQvVvhpKCxT6vWYzp6tGhk6aeO/WvmNvrq52WCBdGhckIa29Bl6ud9o7wOOKqhfbCuXIC9cHKn693slJ9VbW7Hf/kR/RJAMC+RuBG+vSwdBNCcmViAeW+zGGUwEoaRv8hxvbexuOZsiseW36WxCSSaXqVQxOTW7Vc6BejtpXtg6MMjwolIFZWrJNaHG/ZsCA6Je7RDv67Iuzg0I2HFq+BuW3BwyKCzx5UT3jqEIz60bBPwRGKiqmBJp5U=
  on:
    tags: true
