language: go
go:
  - "1.8"
script:
  - ./cover.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: ./deploy.sh # Needs GIT_REMOTE_URL_WITH_AUTH
  on:
    branch: release
